import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Eye, EyeOff, Lock } from 'lucide-react'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'

export interface ScriptParameter {
  name: string
  type: 'text' | 'password'
  default: string
  description: string
  required: boolean
}

interface ScriptParameterInputsProps {
  parameters: ScriptParameter[]
  values: Record<string, string>
  onChange: (values: Record<string, string>) => void
  showDescriptions?: boolean
}

export default function ScriptParameterInputs({
  parameters,
  values,
  onChange,
  showDescriptions = true,
}: ScriptParameterInputsProps) {
  const { t } = useTranslation()
  const [showPassword, setShowPassword] = useState<Record<string, boolean>>({})

  if (!parameters || parameters.length === 0) return null

  const handleChange = (paramName: string, value: string) => {
    onChange({ ...values, [paramName]: value })
  }

  const toggleShowPassword = (paramName: string) => {
    setShowPassword((prev) => ({ ...prev, [paramName]: !prev[paramName] }))
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center gap-2">
        <p className="text-sm font-semibold">{t('scriptParameters.title')}</p>
        <Badge variant="outline" className="text-xs">
          {t('scriptParameters.paramCount', { count: parameters.length })}
        </Badge>
      </div>

      {parameters.map((param) => {
        const isPassword = param.type === 'password'
        const shouldShow = showPassword[param.name]
        const currentValue = values[param.name] || ''

        const normalizedParamName = param.name.toLowerCase().replace(/_/g, ' ')
        const normalizedDescription = (param.description || '').toLowerCase().trim()
        const isAutoGenerated =
          !param.description ||
          param.description === '' ||
          normalizedDescription === normalizedParamName ||
          normalizedDescription === `${normalizedParamName} (encrypted)` ||
          normalizedDescription === normalizedParamName.replace(/\b\w/g, (c: string) => c.toUpperCase())

        const helperText = showDescriptions && !isAutoGenerated ? param.description : undefined

        return (
          <div key={param.name} className="flex flex-col gap-1">
            <Label htmlFor={`script-param-${param.name}`}>
              {param.name}
              {param.required && <span className="text-destructive ml-0.5">*</span>}
            </Label>
            <div className="relative">
              {isPassword && (
                <Lock size={16} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-muted-foreground" />
              )}
              <Input
                id={`script-param-${param.name}`}
                type={isPassword && !shouldShow ? 'password' : 'text'}
                value={currentValue}
                onChange={(e) => handleChange(param.name, e.target.value)}
                required={param.required}
                placeholder={param.default || ''}
                className={isPassword ? 'pl-8 pr-9' : ''}
              />
              {isPassword && (
                <Tooltip>
                  <TooltipTrigger asChild>
                    <button
                      type="button"
                      onClick={() => toggleShowPassword(param.name)}
                      className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                    >
                      {shouldShow ? <EyeOff size={16} /> : <Eye size={16} />}
                    </button>
                  </TooltipTrigger>
                  <TooltipContent>
                    {shouldShow ? t('scriptParameters.hidePassword') : t('scriptParameters.showPassword')}
                  </TooltipContent>
                </Tooltip>
              )}
            </div>
            {helperText && <p className="text-xs text-muted-foreground">{helperText}</p>}
          </div>
        )
      })}
    </div>
  )
}
